version: '3.1'

services:

  sosol-api:
    restart: always
    build: .
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - localstack
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - 7777:7777
    command: npm run dev
    env_file: .env

  postgres:
    image: postgres:12.4
    ports:
      - 5432:5432
    volumes:
      - .pgdata/db:/var/lib/postgresql
      - .pgdata/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sosol_dev
    restart: unless-stopped

  localstack:
      image: localstack/localstack:latest
      ports:
        - '4566-4583:4566-4583'
      environment:
        - DEFAULT_REGION=us-west-2
        - EDGE_PORT=4566
        - SERVICES=s3
      volumes:
        - .localstack:/tmp/localstack
        - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    name: sosol
